using System.Runtime.InteropServices;

namespace UnityEngine.Internal
{
    // Runtime configuration for the shim. A plain runtime bool (NOT #if) is
    // used so a single assembly serves both the Editor play-mode stand-in and
    // the PS2 target. The stand-in sets UseConsoleLog = true at startup;
    // on target it stays false and calls flow into the native runtime.
    public static class ShimConfig
    {
        public static bool UseConsoleLog;
    }

    // P/Invoke boundary to the ps2ur native runtime (plan ADR-002).
    //
    // Rules for every entry in this file:
    //
    //  - [DllImport("__Internal")]: IL2CPP resolves these at static link time
    //    against the extern "C" functions in runtime/src/bridge/. This is the
    //    officially supported mechanism on statically linked platforms
    //    (iOS/WebGL) and is stable across Unity versions (ADR-002).
    //
    //  - BLITTABLE-ONLY signatures: primitives, structs of primitives
    //    (Vector3, Matrix4x4, ...), IntPtr/raw pointers. No classes, no
    //    delegates, no arrays without explicit pinning, and no bool -- C++
    //    bool is 1 byte while System.Boolean marshals as the 4-byte Win32
    //    BOOL, so use int with 0/non-0 semantics.
    //    System.String is the single tolerated exception (IL2CPP marshals it
    //    to a NUL-terminated char*), permitted as an INPUT PARAMETER ONLY on
    //    logging/diagnostic paths -- never as a return value or struct field.
    //    The full table lives in docs/adr/ADR-002-managed-native-boundary.md
    //    ("Boundary type policy"); tools/bindgen enforces it as type 'cstr'.
    //
    //  - This file will eventually be OWNED AND GENERATED by tools/bindgen,
    //    which emits both this class and the matching C prototypes.
    //    TODO(spec missing: section 12): until the bindgen spec (section 12.4
    //    per ADR-002) arrives, entries here are hand-written and provisional.
    //
    // In-Editor: the native runtime does not exist, so callers must check
    // ShimConfig.UseConsoleLog before invoking any Native.* entry (see
    // UnityEngine.Debug for the pattern). Calling an entry in-Editor throws
    // DllNotFoundException by design - it means a shim type forgot its guard.
    internal static class Native
    {
        [DllImport("__Internal")]
        internal static extern void ps2ur_debug_log(string message);
    }
}
