// GENERATED by tools/bindgen/bindgen.py from runtime/src/bridge/bridge-api.json.
// Do not edit by hand; run 'python tools/bindgen/bindgen.py gen-all' (ADR-002).
using System.Runtime.InteropServices;

namespace UnityEngine.Internal
{
    internal static class Native
    {
        // UTF-8 message to the EE console at Info level. Diagnostic path; the per-call string copy is accepted (ADR-002 cstr rules).
        [DllImport("__Internal")]
        internal static extern void ps2ur_debug_log(string message);

        // Creates a root entity (parentHandle 0) or a child. Returns the new handle, or 0 if the entity table is full.
        [DllImport("__Internal")]
        internal static extern int ps2ur_entity_create(int parentHandle);

        // Destroys the entity and its children. The handle's generation is retired: stale handles fail alive() forever after.
        [DllImport("__Internal")]
        internal static extern void ps2ur_entity_destroy(int handle);

        // 1 if the handle refers to a live entity, else 0. This is the native truth behind Unity's destroyed-compares-null semantics.
        [DllImport("__Internal")]
        internal static extern int ps2ur_entity_alive(int handle);

        // GameObject.SetActive: the renderer skips inactive subtrees.
        [DllImport("__Internal")]
        internal static extern void ps2ur_entity_set_active(int handle, int active);

        // activeSelf (not the inherited activeInHierarchy).
        [DllImport("__Internal")]
        internal static extern int ps2ur_entity_get_active(int handle);

        [DllImport("__Internal")]
        internal static extern void ps2ur_tf_get_local_position(int handle, out UnityEngine.Vector3 value);

        [DllImport("__Internal")]
        internal static extern void ps2ur_tf_set_local_position(int handle, float x, float y, float z);

        [DllImport("__Internal")]
        internal static extern void ps2ur_tf_get_local_rotation(int handle, out UnityEngine.Quaternion value);

        [DllImport("__Internal")]
        internal static extern void ps2ur_tf_set_local_rotation(int handle, float x, float y, float z, float w);

        [DllImport("__Internal")]
        internal static extern void ps2ur_tf_get_local_scale(int handle, out UnityEngine.Vector3 value);

        [DllImport("__Internal")]
        internal static extern void ps2ur_tf_set_local_scale(int handle, float x, float y, float z);

        // Parent handle, or 0 for a root entity.
        [DllImport("__Internal")]
        internal static extern int ps2ur_tf_get_parent(int handle);

        // Reparents (parentHandle 0 = make root). Local TRS is NOT adjusted here; Transform.SetParent(worldPositionStays) does that math on the managed side where Unity's semantics live.
        [DllImport("__Internal")]
        internal static extern void ps2ur_tf_set_parent(int handle, int parentHandle);

        [DllImport("__Internal")]
        internal static extern int ps2ur_tf_child_count(int handle);

        // Child handle by index, or 0 if out of range.
        [DllImport("__Internal")]
        internal static extern int ps2ur_tf_get_child(int handle, int index);
    }
}
