namespace UnityEngine.Internal
{
    // Runtime configuration for the shim. A plain runtime bool (NOT #if) is
    // used so a single assembly serves both the Editor play-mode stand-in and
    // the PS2 target. The stand-in sets UseConsoleLog = true at startup;
    // on target it stays false and calls flow into the native runtime.
    //
    // The P/Invoke boundary itself lives in Native.g.cs, GENERATED by
    // tools/bindgen from runtime/src/bridge/bridge-api.json (ADR-002).
    // Editing the extern surface means editing the api-def and re-running
    // 'python tools/bindgen/bindgen.py gen-all' -- never this directory by
    // hand.
    public static class ShimConfig
    {
        public static bool UseConsoleLog;
    }
}
