// GENERATED by tools/bindgen/bindgen.py from runtime/src/bridge/bridge-api.json.
// Do not edit by hand; run 'python tools/bindgen/bindgen.py gen-all' (ADR-002).
#include "generated_bridge.h"

const Ps2urBridgeEntry ps2ur_bridge_table[] = {
    { "ps2ur_debug_log", reinterpret_cast<const void*>(&ps2ur_debug_log) },
    { "ps2ur_entity_create", reinterpret_cast<const void*>(&ps2ur_entity_create) },
    { "ps2ur_entity_destroy", reinterpret_cast<const void*>(&ps2ur_entity_destroy) },
    { "ps2ur_entity_alive", reinterpret_cast<const void*>(&ps2ur_entity_alive) },
    { "ps2ur_entity_set_active", reinterpret_cast<const void*>(&ps2ur_entity_set_active) },
    { "ps2ur_entity_get_active", reinterpret_cast<const void*>(&ps2ur_entity_get_active) },
    { "ps2ur_tf_get_local_position", reinterpret_cast<const void*>(&ps2ur_tf_get_local_position) },
    { "ps2ur_tf_set_local_position", reinterpret_cast<const void*>(&ps2ur_tf_set_local_position) },
    { "ps2ur_tf_get_local_rotation", reinterpret_cast<const void*>(&ps2ur_tf_get_local_rotation) },
    { "ps2ur_tf_set_local_rotation", reinterpret_cast<const void*>(&ps2ur_tf_set_local_rotation) },
    { "ps2ur_tf_get_local_scale", reinterpret_cast<const void*>(&ps2ur_tf_get_local_scale) },
    { "ps2ur_tf_set_local_scale", reinterpret_cast<const void*>(&ps2ur_tf_set_local_scale) },
    { "ps2ur_tf_get_parent", reinterpret_cast<const void*>(&ps2ur_tf_get_parent) },
    { "ps2ur_tf_set_parent", reinterpret_cast<const void*>(&ps2ur_tf_set_parent) },
    { "ps2ur_tf_child_count", reinterpret_cast<const void*>(&ps2ur_tf_child_count) },
    { "ps2ur_tf_get_child", reinterpret_cast<const void*>(&ps2ur_tf_get_child) },
    { "ps2ur_anim_update", reinterpret_cast<const void*>(&ps2ur_anim_update) },
    { "ps2ur_animator_play", reinterpret_cast<const void*>(&ps2ur_animator_play) },
    { "ps2ur_animator_crossfade", reinterpret_cast<const void*>(&ps2ur_animator_crossfade) },
    { "ps2ur_animator_set_trigger", reinterpret_cast<const void*>(&ps2ur_animator_set_trigger) },
    { "ps2ur_animator_set_float", reinterpret_cast<const void*>(&ps2ur_animator_set_float) },
    { "ps2ur_animator_is_blending", reinterpret_cast<const void*>(&ps2ur_animator_is_blending) },
    { "ps2ur_input_update", reinterpret_cast<const void*>(&ps2ur_input_update) },
    { "ps2ur_input_button", reinterpret_cast<const void*>(&ps2ur_input_button) },
    { "ps2ur_input_button_down", reinterpret_cast<const void*>(&ps2ur_input_button_down) },
    { "ps2ur_input_button_up", reinterpret_cast<const void*>(&ps2ur_input_button_up) },
    { "ps2ur_input_axis", reinterpret_cast<const void*>(&ps2ur_input_axis) },
    { "ps2ur_input_pressure", reinterpret_cast<const void*>(&ps2ur_input_pressure) },
    { "ps2ur_input_connected", reinterpret_cast<const void*>(&ps2ur_input_connected) },
    { "ps2ur_input_set_rumble", reinterpret_cast<const void*>(&ps2ur_input_set_rumble) },
    { "ps2ur_scene_load_begin", reinterpret_cast<const void*>(&ps2ur_scene_load_begin) },
    { "ps2ur_scene_load_update", reinterpret_cast<const void*>(&ps2ur_scene_load_update) },
    { "ps2ur_scene_load_progress", reinterpret_cast<const void*>(&ps2ur_scene_load_progress) },
    { "ps2ur_scene_load_state", reinterpret_cast<const void*>(&ps2ur_scene_load_state) },
    { "ps2ur_scene_load_set_allow_activation", reinterpret_cast<const void*>(&ps2ur_scene_load_set_allow_activation) },
};

const int ps2ur_bridge_table_count =
    sizeof(ps2ur_bridge_table) / sizeof(ps2ur_bridge_table[0]);
