// GENERATED by tools/bindgen/bindgen.py from runtime/src/bridge/bridge-api.json.
// Do not edit by hand; run 'python tools/bindgen/bindgen.py gen-all' (ADR-002).
#include "generated_bridge.h"

const Ps2urBridgeEntry ps2ur_bridge_table[] = {
    { "ps2ur_debug_log", reinterpret_cast<const void*>(&ps2ur_debug_log) },
    { "ps2ur_entity_create", reinterpret_cast<const void*>(&ps2ur_entity_create) },
    { "ps2ur_entity_destroy", reinterpret_cast<const void*>(&ps2ur_entity_destroy) },
    { "ps2ur_entity_alive", reinterpret_cast<const void*>(&ps2ur_entity_alive) },
    { "ps2ur_entity_set_active", reinterpret_cast<const void*>(&ps2ur_entity_set_active) },
    { "ps2ur_entity_get_active", reinterpret_cast<const void*>(&ps2ur_entity_get_active) },
    { "ps2ur_tf_get_local_position", reinterpret_cast<const void*>(&ps2ur_tf_get_local_position) },
    { "ps2ur_tf_set_local_position", reinterpret_cast<const void*>(&ps2ur_tf_set_local_position) },
    { "ps2ur_tf_get_local_rotation", reinterpret_cast<const void*>(&ps2ur_tf_get_local_rotation) },
    { "ps2ur_tf_set_local_rotation", reinterpret_cast<const void*>(&ps2ur_tf_set_local_rotation) },
    { "ps2ur_tf_get_local_scale", reinterpret_cast<const void*>(&ps2ur_tf_get_local_scale) },
    { "ps2ur_tf_set_local_scale", reinterpret_cast<const void*>(&ps2ur_tf_set_local_scale) },
    { "ps2ur_tf_get_parent", reinterpret_cast<const void*>(&ps2ur_tf_get_parent) },
    { "ps2ur_tf_set_parent", reinterpret_cast<const void*>(&ps2ur_tf_set_parent) },
    { "ps2ur_tf_child_count", reinterpret_cast<const void*>(&ps2ur_tf_child_count) },
    { "ps2ur_tf_get_child", reinterpret_cast<const void*>(&ps2ur_tf_get_child) },
};

const int ps2ur_bridge_table_count =
    sizeof(ps2ur_bridge_table) / sizeof(ps2ur_bridge_table[0]);
