// GENERATED by tools/bindgen/bindgen.py from runtime/src/bridge/bridge-api.json.
// Do not edit by hand; run 'python tools/bindgen/bindgen.py gen-all' (ADR-002).
#pragma once

#include <stddef.h>
#include <stdint.h>

// Blittable boundary structs. The static_asserts pin the layout the
// managed side assumes; if one fires, the api-def and the C# struct
// have diverged and NOTHING will work until they agree again.

typedef struct P2Vec3 {
    float x;
    float y;
    float z;
} P2Vec3;
static_assert(sizeof(P2Vec3) == 12, "P2Vec3 size drifted from the api-def");
static_assert(offsetof(P2Vec3, x) == 0, "P2Vec3.x offset drifted");
static_assert(offsetof(P2Vec3, y) == 4, "P2Vec3.y offset drifted");
static_assert(offsetof(P2Vec3, z) == 8, "P2Vec3.z offset drifted");

typedef struct P2Quat {
    float x;
    float y;
    float z;
    float w;
} P2Quat;
static_assert(sizeof(P2Quat) == 16, "P2Quat size drifted from the api-def");
static_assert(offsetof(P2Quat, x) == 0, "P2Quat.x offset drifted");
static_assert(offsetof(P2Quat, y) == 4, "P2Quat.y offset drifted");
static_assert(offsetof(P2Quat, z) == 8, "P2Quat.z offset drifted");
static_assert(offsetof(P2Quat, w) == 12, "P2Quat.w offset drifted");

extern "C" {

// UTF-8 message to the EE console at Info level. Diagnostic path; the per-call string copy is accepted (ADR-002 cstr rules).
void ps2ur_debug_log(const char* message);
// Creates a root entity (parentHandle 0) or a child. Returns the new handle, or 0 if the entity table is full.
int32_t ps2ur_entity_create(int32_t parentHandle);
// Destroys the entity and its children. The handle's generation is retired: stale handles fail alive() forever after.
void ps2ur_entity_destroy(int32_t handle);
// 1 if the handle refers to a live entity, else 0. This is the native truth behind Unity's destroyed-compares-null semantics.
int32_t ps2ur_entity_alive(int32_t handle);
// GameObject.SetActive: the renderer skips inactive subtrees.
void ps2ur_entity_set_active(int32_t handle, int32_t active);
// activeSelf (not the inherited activeInHierarchy).
int32_t ps2ur_entity_get_active(int32_t handle);
void ps2ur_tf_get_local_position(int32_t handle, P2Vec3* value);
void ps2ur_tf_set_local_position(int32_t handle, float x, float y, float z);
void ps2ur_tf_get_local_rotation(int32_t handle, P2Quat* value);
void ps2ur_tf_set_local_rotation(int32_t handle, float x, float y, float z, float w);
void ps2ur_tf_get_local_scale(int32_t handle, P2Vec3* value);
void ps2ur_tf_set_local_scale(int32_t handle, float x, float y, float z);
// Parent handle, or 0 for a root entity.
int32_t ps2ur_tf_get_parent(int32_t handle);
// Reparents (parentHandle 0 = make root). Local TRS is NOT adjusted here; Transform.SetParent(worldPositionStays) does that math on the managed side where Unity's semantics live.
void ps2ur_tf_set_parent(int32_t handle, int32_t parentHandle);
int32_t ps2ur_tf_child_count(int32_t handle);
// Child handle by index, or 0 if out of range.
int32_t ps2ur_tf_get_child(int32_t handle, int32_t index);
// Advances every animator by dt and writes their root motion back to entity transforms. The managed dispatcher calls this AFTER Update and coroutines and BEFORE LateUpdate, which is the ordering Unity users rely on (M9 task 4).
void ps2ur_anim_update(float dt);
// Jumps the entity's animator to the named baked state with no blend. Returns 1 when the state exists, 0 otherwise. Names are FNV-1a-64 hashes truncated to 32 bits, matching the exporter.
int32_t ps2ur_animator_play(int32_t handle, uint32_t stateHash);
// Starts a crossfade to the named state over a duration in SECONDS. Returns 1 when the state exists.
int32_t ps2ur_animator_crossfade(int32_t handle, uint32_t stateHash, float seconds);
void ps2ur_animator_set_trigger(int32_t handle, uint32_t paramHash);
void ps2ur_animator_set_float(int32_t handle, uint32_t paramHash, float value);
// 1 while a crossfade is running on the entity's animator.
int32_t ps2ur_animator_is_blending(int32_t handle);

} // extern "C"

// Registration table: referencing every symbol here forces the linker
// to keep the implementations and lets bridge::init() assert that the
// boundary is complete at startup instead of faulting mid-frame.
struct Ps2urBridgeEntry {
    const char* name;
    const void* fn;
};
extern const Ps2urBridgeEntry ps2ur_bridge_table[];
extern const int ps2ur_bridge_table_count;
