namespace UnityEngine
{
    public static class Time
    {
        private static float s_Time;
        private static float s_DeltaTime;
        private static float s_UnscaledTime;
        private static float s_FixedDeltaTime = 0.02f;
        private static int s_FrameCount;

        public static float time => s_Time;
        public static float deltaTime => s_DeltaTime;
        public static float unscaledTime => s_UnscaledTime;
        public static int frameCount => s_FrameCount;

        public static float fixedDeltaTime
        {
            get => s_FixedDeltaTime;
            set => s_FixedDeltaTime = value;
        }

        // Called once per frame by the native runtime (through a bridge
        // wrapper in this assembly, to be generated by tools/bindgen -
        // TODO(spec missing: section 12)) or by the Editor play-mode stand-in
        // (which sees this via InternalsVisibleTo).
        internal static void Sync(float time, float deltaTime, float unscaledTime, float fixedDeltaTime, int frameCount)
        {
            s_Time = time;
            s_DeltaTime = deltaTime;
            s_UnscaledTime = unscaledTime;
            s_FixedDeltaTime = fixedDeltaTime;
            s_FrameCount = frameCount;
        }
    }
}
