#!/usr/bin/env python3
"""bindgen - managed <-> native binding generator (ADR-002, plan 12.4).

Reads the api-def (single source of truth for the P/Invoke boundary) and
emits BOTH sides plus the documentation:

  gen-cs    C# [DllImport("__Internal")] extern declarations (Native.g.cs)
  gen-cpp   C++ extern "C" prototypes, blittable struct definitions with
            static_assert layout pins, and a registration table that forces
            every symbol to be linked and lets the runtime assert at startup
  gen-docs  markdown table of the whole bridge surface
  gen-all   all of the above into their canonical repo locations
  check     regenerate in memory and fail (exit 1) if any committed output
            is stale -- run by CI and the runtime configure step

Generated files are committed; hand-editing them is forbidden. The
implementations of the C prototypes live in runtime/src/bridge/
bridge_impl.cpp, written by hand against the generated header.
"""

import argparse
import io
import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
API_DEF_DEFAULT = os.path.join(REPO_ROOT, "runtime", "src", "bridge", "bridge-api.json")

# Canonical outputs for gen-all / check.
OUT_CS = os.path.join(REPO_ROOT, "managed", "PS2.UnityShim", "Internal", "Native.g.cs")
OUT_H = os.path.join(REPO_ROOT, "runtime", "src", "bridge", "generated_bridge.h")
OUT_CPP = os.path.join(REPO_ROOT, "runtime", "src", "bridge", "generated_bridge.cpp")
OUT_MD = os.path.join(REPO_ROOT, "docs", "bridge-surface.md")

# Boundary type vocabulary (ADR-002 "Boundary type policy").
#
# 'bool' is deliberately ABSENT: C++ bool is 1 byte but the CLR's default
# P/Invoke marshalling for System.Boolean is the 4-byte Win32 BOOL, so a
# bool crossing the boundary silently disagrees about its own width. Use i32
# with 0/non-0 semantics.
PRIMITIVE_TYPES = {
    "void",
    "u8", "i8", "u16", "i16", "u32", "i32", "u64", "i64",
    "f32", "f64",
}

# 'cstr' is the single non-blittable type the boundary tolerates: a read-only,
# NUL-terminated UTF-8 string that IL2CPP marshals from System.String to
# const char*. It is INPUT-ONLY and restricted to diagnostic paths (logging,
# assertions, profiler labels) where the per-call copy is irrelevant. It may
# never be a return type or a struct field -- that would make the native side
# own an allocation the managed side must free, and this boundary defines no
# protocol for that.
CSTR_TYPE = "cstr"

C_TYPES = {
    "void": "void",
    "u8": "uint8_t", "i8": "int8_t",
    "u16": "uint16_t", "i16": "int16_t",
    "u32": "uint32_t", "i32": "int32_t",
    "u64": "uint64_t", "i64": "int64_t",
    "f32": "float", "f64": "double",
    CSTR_TYPE: "const char*",
}

CS_TYPES = {
    "void": "void",
    "u8": "byte", "i8": "sbyte",
    "u16": "ushort", "i16": "short",
    "u32": "uint", "i32": "int",
    "u64": "ulong", "i64": "long",
    "f32": "float", "f64": "double",
    CSTR_TYPE: "string",
}

PRIMITIVE_SIZES = {
    "u8": 1, "i8": 1, "u16": 2, "i16": 2,
    "u32": 4, "i32": 4, "u64": 8, "i64": 8,
    "f32": 4, "f64": 8,
}

GENERATED_BANNER = (
    "GENERATED by tools/bindgen/bindgen.py from runtime/src/bridge/"
    "bridge-api.json.\nDo not edit by hand; run 'python tools/bindgen/"
    "bindgen.py gen-all' (ADR-002)."
)


class ApiDefError(Exception):
    """Raised for any structural problem in an api-def file."""


def load_api_def(path):
    """Load and validate an api-def file. Returns the parsed dict."""
    if not os.path.isfile(path):
        raise ApiDefError("api-def not found: %s" % path)
    ext = os.path.splitext(path)[1].lower()
    with open(path, "r", encoding="utf-8") as fh:
        text = fh.read()
    if ext in (".yaml", ".yml"):
        try:
            import yaml  # type: ignore
        except ImportError:
            raise ApiDefError(
                "PyYAML is not installed; use a .json api-def or "
                "'pip install pyyaml'")
        data = yaml.safe_load(text)
    elif ext == ".json":
        try:
            data = json.loads(text)
        except ValueError as exc:
            raise ApiDefError("invalid JSON in %s: %s" % (path, exc))
    else:
        raise ApiDefError(
            "unsupported api-def extension '%s' (expected .yaml/.yml/.json)"
            % ext)
    _validate(data, path)
    return data


def _validate(data, path):
    if not isinstance(data, dict):
        raise ApiDefError("%s: top level must be a mapping" % path)
    for key in ("module", "functions"):
        if key not in data:
            raise ApiDefError("%s: missing required top-level key '%s'"
                              % (path, key))
    if not isinstance(data["functions"], list):
        raise ApiDefError("%s: 'functions' must be a list" % path)

    struct_names = set()
    for i, struct in enumerate(data.get("types", []) or []):
        if not isinstance(struct, dict) or "name" not in struct:
            raise ApiDefError("%s: types[%d] must be a mapping with 'name'"
                              % (path, i))
        struct_names.add(struct["name"])
        for j, field in enumerate(struct.get("fields", []) or []):
            _check_type(field, "types[%d].fields[%d]" % (i, j),
                        struct_names, path, allow_void=False, kind="field")
            if field["type"].endswith("*") or field["type"] not in PRIMITIVE_TYPES:
                if field["type"] not in PRIMITIVE_TYPES:
                    raise ApiDefError(
                        "%s: types[%d].fields[%d]: struct fields must be "
                        "primitives (nested structs/pointers would need a "
                        "layout story this boundary does not define)"
                        % (path, i, j))

    for i, fn in enumerate(data["functions"]):
        if not isinstance(fn, dict):
            raise ApiDefError("%s: functions[%d] must be a mapping" % (path, i))
        for key in ("name", "cs_class", "returns"):
            if key not in fn:
                raise ApiDefError("%s: functions[%d] missing '%s'"
                                  % (path, i, key))
        _check_type({"name": "return", "type": fn["returns"]},
                    "functions[%d].returns" % i, struct_names, path,
                    allow_void=True, kind="return")
        for j, param in enumerate(fn.get("params", []) or []):
            where = "functions[%d].params[%d]" % (i, j)
            _check_type(param, where, struct_names, path,
                        allow_void=False, kind="param")
            if "dir" in param:
                if param["dir"] not in ("out", "ref"):
                    raise ApiDefError("%s: %s: dir must be 'out' or 'ref'"
                                      % (path, where))
                if not param["type"].endswith("*"):
                    raise ApiDefError(
                        "%s: %s: dir is only meaningful on struct pointer "
                        "parameters" % (path, where))


def _check_type(entry, where, struct_names, path, allow_void, kind="param"):
    if not isinstance(entry, dict) or "name" not in entry or "type" not in entry:
        raise ApiDefError("%s: %s must be a mapping with 'name' and 'type'"
                          % (path, where))
    tname = entry["type"]
    base = tname[:-1] if tname.endswith("*") else tname
    if base == "void" and not (allow_void and base == tname):
        raise ApiDefError("%s: %s: 'void' only valid as a return type"
                          % (path, where))
    if base == CSTR_TYPE:
        # Input-only, diagnostics-only. See CSTR_TYPE for the rationale.
        if tname != CSTR_TYPE:
            raise ApiDefError(
                "%s: %s: '%s' is not a valid type; 'cstr' is already a "
                "pointer and may not be decorated (ADR-002)"
                % (path, where, tname))
        if kind != "param":
            raise ApiDefError(
                "%s: %s: 'cstr' is input-only -- it may not be used as a %s "
                "(ADR-002: the boundary has no protocol for native-owned "
                "string lifetimes)" % (path, where, kind))
        return
    if base in PRIMITIVE_TYPES or base in struct_names:
        if base == "f64":
            sys.stderr.write(
                "bindgen: warning: %s: f64 crosses the boundary at %s "
                "(soft-float on the EE; see plan section 3.1)\n"
                % (path, where))
        return
    if base == "bool":
        raise ApiDefError(
            "%s: %s: 'bool' may not cross the boundary -- C++ bool is 1 byte "
            "but System.Boolean marshals as the 4-byte Win32 BOOL. Use 'i32' "
            "with 0/non-0 semantics (ADR-002)." % (path, where))
    raise ApiDefError(
        "%s: %s: type '%s' is not a primitive, 'cstr', or a declared blittable "
        "struct (blittable-only boundary, ADR-002)" % (path, where, tname))


# ---- layout ---------------------------------------------------------------

def struct_layout(struct):
    """(fields with offsets, total size, max alignment) under natural C
    layout. Fields are primitives only (validated), so align == size."""
    offset = 0
    max_align = 1
    rows = []
    for field in struct.get("fields", []) or []:
        size = PRIMITIVE_SIZES[field["type"]]
        align = size
        offset = (offset + align - 1) & ~(align - 1)
        rows.append((field["name"], field["type"], offset, size))
        offset += size
        max_align = max(max_align, align)
    total = (offset + max_align - 1) & ~(max_align - 1)
    return rows, total, max_align


# ---- type rendering -------------------------------------------------------

def c_type(tname):
    if tname.endswith("*"):
        return c_type(tname[:-1]) + "*"
    return C_TYPES.get(tname, tname)


def cs_struct_name(api, name):
    for struct in api.get("types", []) or []:
        if struct["name"] == name:
            return struct.get("cs", name)
    return name


def cs_param(api, param):
    tname = param["type"]
    if tname.endswith("*"):
        base = tname[:-1]
        direction = param.get("dir", "ref")
        return "%s %s %s" % (direction, cs_struct_name(api, base), param["name"])
    return "%s %s" % (CS_TYPES.get(tname, cs_struct_name(api, tname)), param["name"])


def cs_return(api, tname):
    return CS_TYPES.get(tname, cs_struct_name(api, tname))


# ---- emitters -------------------------------------------------------------

def emit_cs(api):
    out = io.StringIO()
    out.write("// %s\n" % GENERATED_BANNER.replace("\n", "\n// "))
    out.write("using System.Runtime.InteropServices;\n\n")

    by_class = {}
    for fn in api["functions"]:
        by_class.setdefault(fn["cs_class"], []).append(fn)

    for cls in sorted(by_class):
        namespace, _, class_name = cls.rpartition(".")
        out.write("namespace %s\n{\n" % namespace)
        out.write("    internal static class %s\n    {\n" % class_name)
        first = True
        for fn in by_class[cls]:
            if not first:
                out.write("\n")
            first = False
            if "doc" in fn:
                out.write("        // %s\n" % fn["doc"])
            params = ", ".join(cs_param(api, p) for p in fn.get("params", []) or [])
            out.write("        [DllImport(\"__Internal\")]\n")
            out.write("        internal static extern %s %s(%s);\n"
                      % (cs_return(api, fn["returns"]), fn["name"], params))
        out.write("    }\n}\n")
    return out.getvalue()


def emit_cpp_header(api):
    out = io.StringIO()
    out.write("// %s\n" % GENERATED_BANNER.replace("\n", "\n// "))
    out.write("#pragma once\n\n#include <stddef.h>\n#include <stdint.h>\n\n")
    out.write("// Blittable boundary structs. The static_asserts pin the layout the\n")
    out.write("// managed side assumes; if one fires, the api-def and the C# struct\n")
    out.write("// have diverged and NOTHING will work until they agree again.\n")
    for struct in api.get("types", []) or []:
        rows, total, _align = struct_layout(struct)
        out.write("\ntypedef struct %s {\n" % struct["name"])
        for name, tname, _off, _size in rows:
            out.write("    %s %s;\n" % (c_type(tname), name))
        out.write("} %s;\n" % struct["name"])
        out.write("static_assert(sizeof(%s) == %d, \"%s size drifted from the api-def\");\n"
                  % (struct["name"], total, struct["name"]))
        for name, _tname, off, _size in rows:
            out.write("static_assert(offsetof(%s, %s) == %d, \"%s.%s offset drifted\");\n"
                      % (struct["name"], name, off, struct["name"], name))

    out.write("\nextern \"C\" {\n\n")
    for fn in api["functions"]:
        if "doc" in fn:
            out.write("// %s\n" % fn["doc"])
        params = ", ".join("%s %s" % (c_type(p["type"]), p["name"])
                           for p in fn.get("params", []) or []) or "void"
        out.write("%s %s(%s);\n" % (c_type(fn["returns"]), fn["name"], params))
    out.write("\n} // extern \"C\"\n\n")

    out.write("// Registration table: referencing every symbol here forces the linker\n")
    out.write("// to keep the implementations and lets bridge::init() assert that the\n")
    out.write("// boundary is complete at startup instead of faulting mid-frame.\n")
    out.write("struct Ps2urBridgeEntry {\n    const char* name;\n    const void* fn;\n};\n")
    out.write("extern const Ps2urBridgeEntry ps2ur_bridge_table[];\n")
    out.write("extern const int ps2ur_bridge_table_count;\n")
    return out.getvalue()


def emit_cpp_table(api):
    out = io.StringIO()
    out.write("// %s\n" % GENERATED_BANNER.replace("\n", "\n// "))
    out.write("#include \"generated_bridge.h\"\n\n")
    out.write("const Ps2urBridgeEntry ps2ur_bridge_table[] = {\n")
    for fn in api["functions"]:
        out.write("    { \"%s\", reinterpret_cast<const void*>(&%s) },\n"
                  % (fn["name"], fn["name"]))
    out.write("};\n\n")
    out.write("const int ps2ur_bridge_table_count =\n"
              "    sizeof(ps2ur_bridge_table) / sizeof(ps2ur_bridge_table[0]);\n")
    return out.getvalue()


def emit_docs(api):
    out = io.StringIO()
    out.write("# Bridge surface\n\n")
    out.write("<!-- %s -->\n\n" % GENERATED_BANNER.replace("\n", " "))
    out.write("The complete managed<->native boundary (ADR-002). %d functions, "
              "%d shared structs.\n\n"
              % (len(api["functions"]), len(api.get("types", []) or [])))
    out.write("## Structs\n\n")
    for struct in api.get("types", []) or []:
        rows, total, _ = struct_layout(struct)
        out.write("### `%s` (%d bytes) = `%s`\n\n"
                  % (struct["name"], total, struct.get("cs", struct["name"])))
        out.write("| field | type | offset |\n|---|---|---|\n")
        for name, tname, off, _size in rows:
            out.write("| `%s` | `%s` | %d |\n" % (name, tname, off))
        out.write("\n")
    out.write("## Functions\n\n")
    out.write("| symbol | signature | notes |\n|---|---|---|\n")
    for fn in api["functions"]:
        params = ", ".join("%s %s" % (p["type"] + ("/" + p["dir"] if "dir" in p else ""),
                                      p["name"])
                           for p in fn.get("params", []) or [])
        out.write("| `%s` | `%s(%s)` | %s |\n"
                  % (fn["name"], fn["returns"], params, fn.get("doc", "")))
    return out.getvalue()


# ---- commands -------------------------------------------------------------

def _write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="ascii", newline="\n") as fh:
        fh.write(content)
    print("bindgen: wrote %s" % os.path.relpath(path, REPO_ROOT))


def _outputs(api):
    return {
        OUT_CS: emit_cs(api),
        OUT_H: emit_cpp_header(api),
        OUT_CPP: emit_cpp_table(api),
        OUT_MD: emit_docs(api),
    }


def cmd_gen_cs(args):
    api = load_api_def(args.api_def)
    _write(os.path.join(args.out, "Native.g.cs"), emit_cs(api))
    return 0


def cmd_gen_cpp(args):
    api = load_api_def(args.api_def)
    _write(os.path.join(args.out, "generated_bridge.h"), emit_cpp_header(api))
    _write(os.path.join(args.out, "generated_bridge.cpp"), emit_cpp_table(api))
    return 0


def cmd_gen_docs(args):
    api = load_api_def(args.api_def)
    _write(os.path.join(args.out, "bridge-surface.md"), emit_docs(api))
    return 0


def cmd_gen_all(args):
    api = load_api_def(args.api_def)
    for path, content in _outputs(api).items():
        _write(path, content)
    return 0


def cmd_check(args):
    api = load_api_def(args.api_def)
    stale = []
    for path, content in _outputs(api).items():
        try:
            with open(path, "r", encoding="ascii", newline="") as fh:
                on_disk = fh.read()
        except OSError:
            on_disk = None
        if on_disk != content:
            stale.append(os.path.relpath(path, REPO_ROOT))
    if stale:
        sys.stderr.write(
            "bindgen: STALE generated files (run 'python tools/bindgen/"
            "bindgen.py gen-all'):\n")
        for path in stale:
            sys.stderr.write("  %s\n" % path)
        return 1
    print("bindgen: check OK (%d files current)" % len(_outputs(api)))
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="bindgen",
        description="Generate both sides of the PS2.UnityShim <-> ps2ur "
                    "P/Invoke boundary from an api-def file (ADR-002).")
    sub = parser.add_subparsers(dest="command")
    sub.required = True

    def add(name, func, help_text, with_out=True):
        p = sub.add_parser(name, help=help_text)
        p.add_argument("api_def", nargs="?", default=API_DEF_DEFAULT,
                       help="path to api-def (default: %(default)s)")
        if with_out:
            p.add_argument("-o", "--out", required=True,
                           help="output directory")
        p.set_defaults(func=func)
        return p

    add("gen-cs", cmd_gen_cs,
        "emit C# [DllImport(\"__Internal\")] extern declarations")
    add("gen-cpp", cmd_gen_cpp,
        "emit C++ extern \"C\" prototypes and the registration table")
    add("gen-docs", cmd_gen_docs, "emit the bridge surface markdown table")
    add("gen-all", cmd_gen_all,
        "regenerate every output in its canonical repo location",
        with_out=False)
    add("check", cmd_check,
        "verify the committed generated files are current (CI)",
        with_out=False)

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except ApiDefError as exc:
        sys.stderr.write("bindgen: error: %s\n" % exc)
        return 1


if __name__ == "__main__":
    sys.exit(main())
