// The generic game host (plan section 13, M12): the ELF a Unity build
// produces.
//
// Derived from main_m7.cpp, which proved this bring-up sequence at M7. The
// differences are all subtractive -- what made that file a test harness is
// gone -- plus one addition: everything scene-specific now comes from
// game_config.h, which the build pipeline generates from the build profile.
//
// Boot sequence, in the order it has to happen:
//   1. Capture the stack bottom for bdwgc BEFORE anything allocates.
//   2. Bring up the GS.
//   3. Load the boot scene container into a scene::World.
//   4. bridge::bind_world, so managed Transform/GameObject resolve.
//   5. il2cpp_init, then find UnityEngine.Internal.Runtime.
//   6. CreateScript for every script component the scene carries.
//   7. Frame loop for as long as the console is on: Runtime.Tick(dt) ->
//      world matrices -> VU1 render.
//
// The loop runs forever by design. A shipped title never falls off the end
// of main(): returning hands control back to the BIOS, which shows the
// memory-card browser (verify-log M0).
#include <ps2ur/alloc.h>
#include <ps2ur/audio.h>
#include <ps2ur/bridge.h>
#include <ps2ur/input.h>
#include <ps2ur/dma_chain.h>
#include <ps2ur/gs_batch.h>
#include <ps2ur/gs_device.h>
#include <ps2ur/log.h>
#include <ps2ur/math.h>
#include <ps2ur/p2b.h>
#include <ps2ur/p2b_scene.h>
#include <ps2ur/scene_renderer.h>
#include <ps2ur/phys.h>
#include <ps2ur/phys_bake.h>
#include <ps2ur/platform.h>
#include <ps2ur/vu_program.h>

#include <kernel.h>
#include <malloc.h>
#include <stdio.h>

#include "il2cpp-api.h"
#include "il2cpp-class-internals.h"

// Generated by the build pipeline from the build profile. Carries the boot
// scene name, the video mode and the memory budgets, so this file has
// nothing scene-specific compiled into it.
#include "game_config.h"

using namespace ps2ur;

extern "C" u32 VuUnlit_CodeStart __attribute__((section(".vudata")));
extern "C" u32 VuUnlit_CodeEnd __attribute__((section(".vudata")));
extern "C" u32 VuUnlitTex_CodeStart __attribute__((section(".vudata")));
extern "C" u32 VuUnlitTex_CodeEnd __attribute__((section(".vudata")));
extern "C" u32 VuLitFog_CodeStart __attribute__((section(".vudata")));
extern "C" u32 VuLitFog_CodeEnd __attribute__((section(".vudata")));
extern "C" u32 VuSkin_CodeStart __attribute__((section(".vudata")));
extern "C" u32 VuSkin_CodeEnd __attribute__((section(".vudata")));
extern "C" u32 VuLit_CodeStart __attribute__((section(".vudata")));
extern "C" u32 VuLit_CodeEnd __attribute__((section(".vudata")));

// bdwgc stack bound (see il2cpp-port/os/ps2/GcSupport.cpp).
extern "C" char* ps2ur_gc_stack_bottom;

namespace {

// The addresses scene::RendererPrograms defaults to; keep them in step.
constexpr uint32_t kAddrUnlit = 0;
constexpr uint32_t kAddrTex = 300;
constexpr uint32_t kAddrLit = 700;
constexpr uint32_t kAddrLitFog = 1000;
constexpr uint32_t kAddrSkin = 1300;

// VRAM holds the two colour buffers and the depth buffer, so what is left is
// what textures get. Eight 256x256 PSMT8 pages plus CLUTs fits comfortably.
constexpr uint32_t kMaxGpuTextures = 8;

struct GpuTexture {
    gfx::VramAlloc tex;
    gfx::VramAlloc clut;
    uint32_t w = 0, h = 0;
};

struct BindContext {
    gfx::GsDevice* device;
    GpuTexture* textures;
    uint32_t count;
};

void bind_texture(void* user, uint32_t index)
{
    BindContext* ctx = static_cast<BindContext*>(user);
    if (index >= ctx->count) {
        return;
    }
    GpuTexture& t = ctx->textures[index];
    ctx->device->set_texture_indexed(t.tex, t.w, t.h, gfx::PixelFormat::PSMT8,
                                     t.clut, 256);
}

uint32_t rd_u32(const uint8_t* p)
{
    return static_cast<uint32_t>(p[0]) | (static_cast<uint32_t>(p[1]) << 8) |
           (static_cast<uint32_t>(p[2]) << 16) |
           (static_cast<uint32_t>(p[3]) << 24);
}

// The scene arena.
//
// This was a 2 MB static array, on the reasoning that .bss is claimed before
// il2cpp asks for anything: at the profile's 6 MB default, on top of an 11 MB
// development ELF, that is 17 MB of 32 committed before the metadata (~1-2 MB)
// and the GC heap (4 MB) are allocated at all -- and il2cpp's metadata loader
// writes through the null it gets back rather than checking, so the symptom
// was stores to address 0x0 rather than an out-of-memory message
// (verify-log M12).
//
// The reasoning was right about .bss and wrong about 2 MB. A scene with one
// imported character in it is 5-6 MB, so a fixed 2 MB does not fail at the
// margin, it fails on the first real scene (verify-log M12.5).
//
// Taking it from the heap keeps what mattered -- nothing is committed that is
// not used -- while letting the profile's assetPoolMb actually govern the
// size, which it never did before. This runs before bridge::init(), so it is
// still ahead of every il2cpp allocation.
constexpr uint32_t kBootSceneArenaBytes = PS2_GAME_ASSET_POOL_BYTES;
alignas(16) gfx::Qword g_constants[17];

void set_float4(gfx::Qword& q, float x, float y, float z, float w)
{
    union {
        float f;
        uint32_t u;
    } cx{x}, cy{y}, cz{z}, cw{w};
    q.lo = static_cast<uint64_t>(cx.u) | (static_cast<uint64_t>(cy.u) << 32);
    q.hi = static_cast<uint64_t>(cz.u) | (static_cast<uint64_t>(cw.u) << 32);
}

const MethodInfo* find_runtime_method(const char* name, int params)
{
    const Il2CppDomain* domain = il2cpp_domain_get();
    size_t count = 0;
    const Il2CppAssembly** assemblies = il2cpp_domain_get_assemblies(domain, &count);
    for (size_t i = 0; i < count; ++i) {
        const Il2CppImage* image = il2cpp_assembly_get_image(assemblies[i]);
        Il2CppClass* klass =
            il2cpp_class_from_name(image, "UnityEngine.Internal", "Runtime");
        if (klass != nullptr) {
            const MethodInfo* method =
                il2cpp_class_get_method_from_name(klass, name, params);
            if (method != nullptr) {
                return method;
            }
        }
    }
    return nullptr;
}

// A managed call that reports rather than swallows. An exception escaping
// into native code with nobody looking is how a game "just stops"; printing
// it costs nothing and is the difference between a bug report and a mystery.
bool invoke_checked(const MethodInfo* method, void** args, const char* what)
{
    Il2CppException* exception = nullptr;
    il2cpp_runtime_invoke(const_cast<MethodInfo*>(method), nullptr, args, &exception);
    if (exception != nullptr) {
        static char message[512];
        il2cpp_format_exception(exception, message, sizeof(message));
        printf("[game] %s threw: %s\n", what, message);
        return false;
    }
    return true;
}

// A fatal error parks rather than returns, for the reason in the header.
void fatal(const char* what)
{
    printf("PS2UR_TOKEN_GAME_FAIL %s\n", what);
    SleepThread();
}

} // namespace

int main(void)
{
    int stackAnchor;
    ps2ur_gc_stack_bottom = reinterpret_cast<char*>(
        (reinterpret_cast<unsigned long>(&stackAnchor) + 128) & ~15UL);

    platform::init();
    printf("[game] %s starting\n", PS2_GAME_PRODUCT_NAME);

    // --- GS -----------------------------------------------------------------
    gfx::VideoConfig config;
    config.width = PS2_GAME_SCREEN_WIDTH;
    config.height = PS2_GAME_SCREEN_HEIGHT;

    gfx::GsDevice device;
    if (!device.init(config)) {
        fatal("gs device");
        return 1;
    }

    // --- Boot scene ---------------------------------------------------------
    Arena file_arena;
    void* file_arena_mem = memalign(16, kBootSceneArenaBytes);
    if (file_arena_mem == nullptr) {
        printf("[game] could not reserve the %u MB asset pool. Lower Asset "
               "Pool in the PS2 build profile, or the managed heap beside "
               "it.\n",
               static_cast<unsigned>(kBootSceneArenaBytes / (1024u * 1024u)));
        fatal("asset pool");
        return 1;
    }
    file_arena.init(file_arena_mem, kBootSceneArenaBytes);

    // resolve_media_path tries host:, then the bare name, then
    // cdrom0:\NAME;1 -- so the same ELF runs from the emulator's host
    // filesystem during iteration and from the disc when burned, with no
    // rebuild (M10).
    char scene_path[96];
    if (!io::resolve_media_path(PS2_GAME_BOOT_SCENE, scene_path, sizeof(scene_path))) {
        printf("[game] boot scene '%s' not found on any media\n",
               PS2_GAME_BOOT_SCENE);
        fatal("boot scene missing");
        return 1;
    }
    printf("[game] boot scene: %s\n", scene_path);

    uint32_t file_size = 0;
    const void* file_data = io::load_file(scene_path, file_arena, &file_size);
    if (file_data == nullptr) {
        // The overwhelmingly likely cause is that the scene is bigger than the
        // pool, and the io layer has just printed both numbers. It cannot name
        // the setting to change -- it knows nothing about Unity -- so do it
        // here, where the profile that generated this build is known.
        printf("[game] the boot scene did not fit in the %u MB asset pool. "
               "Raise Asset Pool in the PS2 build profile.\n",
               static_cast<unsigned>(kBootSceneArenaBytes / (1024u * 1024u)));
        fatal("boot scene unreadable");
        return 1;
    }
    io::P2bFile file;
    if (!file.parse(file_data, file_size)) {
        printf("[game] container error: %s\n", file.error());
        fatal("boot scene malformed");
        return 1;
    }
    static scene::World world;
    if (!world.load(file)) {
        printf("[game] scene error: %s\n", world.error());
        fatal("boot scene load");
        return 1;
    }
    printf("[game] scene: %u entities, %u meshes, %u scripts\n",
           static_cast<unsigned>(world.entity_count()),
           static_cast<unsigned>(world.mesh_count()),
           static_cast<unsigned>(world.script_count()));

    if (!bridge::init()) {
        fatal("bridge");
        return 1;
    }
    bridge::bind_world(&world);
    phys::init();

    // Collision. The BVH and the vertices are used straight out of the
    // container, so 'static_mesh' must outlive the world -- hence static
    // storage rather than a stack local whose pointers would dangle the
    // moment main's frame is reused.
    //
    // A scene with no PHYS section loads fine and reports zero colliders;
    // not every scene has collision, and refusing to boot one would be
    // wrong. What is NOT fine is a section that is present and malformed.
    static phys::StaticMesh static_mesh;
    phys::BakeInfo bake;
    const char* phys_error = "";
    if (!phys::load_physics(file, &static_mesh, &bake, &phys_error)) {
        printf("[game] collision: %s\n", phys_error);
        fatal("physics load");
        return 1;
    }
    phys::set_static_mesh(&static_mesh);
    printf("[game] collision: %u colliders, %u triangles, %u nodes\n",
           static_cast<unsigned>(bake.collider_count),
           static_cast<unsigned>(bake.triangle_count),
           static_cast<unsigned>(bake.node_count));

    // Platform services. input::init() brings up sio2man/padman and opens
    // both ports; without it every button reads false forever and
    // Input.GetButtonDown never fires -- the managed side polls happily and
    // gets nothing, which looks like a mapping bug rather than a missing
    // init. Audio is optional: a game with no sound should still boot.
    if (!input::init()) {
        printf("[game] pads failed to initialise; input will not work.\n");
    }
    if (!audio::init()) {
        printf("[game] audio failed to initialise; the game will run silent.\n");
    }

    // --- Managed runtime ----------------------------------------------------
    il2cpp_set_data_dir("host:");
    if (!il2cpp_init("IL2CPP Root Domain")) {
        fatal("il2cpp_init");
        return 1;
    }
    const MethodInfo* create_script = find_runtime_method("CreateScript", 2);
    const MethodInfo* create_rigidbody = find_runtime_method("CreateRigidbody", 5);
    const MethodInfo* bind_colliders = find_runtime_method("BindColliders", 0);
    const MethodInfo* create_animator = find_runtime_method("CreateAnimator", 1);
    const MethodInfo* tick = find_runtime_method("Tick", 1);
    if (create_script == nullptr || tick == nullptr ||
        create_rigidbody == nullptr || bind_colliders == nullptr ||
        create_animator == nullptr) {
        // Almost always a stripping problem: the dispatcher is reached by
        // reflection, so it needs a link.xml entry to survive.
        printf("[game] UnityEngine.Internal.Runtime was not found. It is "
               "reached by reflection, so it must be preserved in link.xml.\n");
        fatal("Runtime methods missing");
        return 1;
    }

    // --- Physics components -------------------------------------------------
    //
    // Before the scripts, deliberately. A script's Start() runs on the first
    // Tick and the very first thing gameplay code does is
    // GetComponent<Rigidbody>(); if the body were created afterwards that
    // call would return null and the script would throw on frame 1.
    if (!invoke_checked(bind_colliders, nullptr, "BindColliders")) {
        fatal("BindColliders");
        return 1;
    }
    for (uint32_t r = 0; r < world.rigidbody_count(); ++r) {
        const scene::RigidbodyRef& rb = world.rigidbody(r);
        int32_t handle = world.handle_of(rb.entity);
        float mass = rb.mass;
        float linear_damping = rb.linear_damping;
        float angular_damping = rb.angular_damping;
        int32_t flags = static_cast<int32_t>(rb.flags);
        void* args[5] = {&handle, &mass, &linear_damping, &angular_damping,
                         &flags};
        if (!invoke_checked(create_rigidbody, args, "CreateRigidbody")) {
            fatal("CreateRigidbody");
            return 1;
        }
    }
    for (uint32_t a = 0; a < world.animator_ref_count(); ++a) {
        int32_t handle = world.handle_of(world.animator_ref(a).entity);
        void* args[1] = {&handle};
        if (!invoke_checked(create_animator, args, "CreateAnimator")) {
            fatal("CreateAnimator");
            return 1;
        }
    }
    if (world.animator_ref_count() > 0 || world.skinned_renderer_count() > 0) {
        printf("[game] %u animator components, %u skinned renderers over %u "
               "meshes, %u skeletons, %u clips, %u animators\n",
               static_cast<unsigned>(world.animator_ref_count()),
               static_cast<unsigned>(world.skinned_renderer_count()),
               static_cast<unsigned>(world.skinned_mesh_count()),
               static_cast<unsigned>(world.skeleton_count()),
               static_cast<unsigned>(world.clip_count()),
               static_cast<unsigned>(world.animator_count()));
    }
    if (world.rigidbody_count() > 0) {
        printf("[game] %u rigidbodies\n",
               static_cast<unsigned>(world.rigidbody_count()));
    }

    // --- Script components --------------------------------------------------
    for (uint32_t s = 0; s < world.script_count(); ++s) {
        const scene::ScriptRef& script = world.script(s);
        Il2CppString* type_name = il2cpp_string_new(script.type_name);
        int32_t handle = world.handle_of(script.entity);
        void* args[2] = {type_name, &handle};
        printf("[game] script '%s' on entity %d\n", script.type_name,
               script.entity);
        if (!invoke_checked(create_script, args, "CreateScript")) {
            fatal("CreateScript");
            return 1;
        }
    }

    // --- Textures -----------------------------------------------------------
    //
    // The host used to skip this entirely, so every TEX section a build
    // produced was dead weight on the disc and every textured material drew
    // with whatever happened to be in VRAM (verify-log M12.5).
    static GpuTexture textures[kMaxGpuTextures];
    uint32_t tex_count = file.count_of(io::kSectionTex);
    if (tex_count > kMaxGpuTextures) {
        printf("[game] %u textures, only %u fit in VRAM; the rest will not "
               "be bound.\n",
               static_cast<unsigned>(tex_count),
               static_cast<unsigned>(kMaxGpuTextures));
        tex_count = kMaxGpuTextures;
    }
    device.begin_frame();
    device.clear(0, 0, 0);
    for (uint32_t t = 0; t < tex_count; ++t) {
        const io::P2bSection* sec = file.find(io::kSectionTex, t);
        const uint8_t* p = sec->data;
        GpuTexture& gt = textures[t];
        gt.w = rd_u32(p + 0);
        gt.h = rd_u32(p + 4);
        gt.tex = device.vram().alloc_buffer(gt.w, gt.h, gfx::PixelFormat::PSMT8,
                                            "game-tex");
        gt.clut = device.vram().alloc_buffer(16, 16, gfx::PixelFormat::PSMCT32,
                                             "game-clut");
        if (!gt.tex.valid() || !gt.clut.valid() ||
            !device.upload_texture(p + 16u + 1024u, gt.tex, gt.w, gt.h,
                                   gfx::PixelFormat::PSMT8) ||
            !device.upload_clut(reinterpret_cast<const uint32_t*>(p + 16u),
                                gt.clut, 256)) {
            printf("[game] texture %u did not fit in VRAM.\n",
                   static_cast<unsigned>(t));
            fatal("texture upload");
            return 1;
        }
    }
    device.end_frame();

    // --- VU programs + DMA chain -------------------------------------------
    //
    // All FIVE, at the addresses scene::RendererPrograms defaults to. Only
    // unlit and lit were uploaded before, which silently ruled out every
    // textured, fogged and skinned material a build could contain.
    vu::MicroProgram prog_unlit, prog_tex, prog_lit, prog_fog, prog_skin;
    prog_unlit.set_blob(&VuUnlit_CodeStart, &VuUnlit_CodeEnd, kAddrUnlit);
    prog_tex.set_blob(&VuUnlitTex_CodeStart, &VuUnlitTex_CodeEnd, kAddrTex);
    prog_lit.set_blob(&VuLit_CodeStart, &VuLit_CodeEnd, kAddrLit);
    prog_fog.set_blob(&VuLitFog_CodeStart, &VuLitFog_CodeEnd, kAddrLitFog);
    prog_skin.set_blob(&VuSkin_CodeStart, &VuSkin_CodeEnd, kAddrSkin);
    if (!prog_unlit.upload() || !prog_tex.upload() || !prog_lit.upload() ||
        !prog_fog.upload() || !prog_skin.upload()) {
        fatal("vu programs");
        return 1;
    }
    gfx::DmaChain chain;
    if (!chain.init(2048)) {
        fatal("dma chain");
        return 1;
    }

    if (!world.has_camera()) {
        printf("[game] the boot scene has no Camera; nothing could be drawn.\n");
        fatal("no camera");
        return 1;
    }
    // The M8/M9 frame path, rather than the hand-rolled loop this host used
    // to carry. That loop walked entities with a rigid mesh and nothing else,
    // so a scene's skinned characters were loaded, animated and never drawn,
    // and its textures never bound (verify-log M12.5). SceneRenderer already
    // does culling, the sorted opaque/transparent passes, material state,
    // fog and the skinned pass -- all of it built and verified in M8 and M9,
    // and all of it unreachable from a Unity build until now.
    scene::SceneRenderer renderer;
    scene::RendererPrograms programs; // 0 / 300 / 700 / 1000 / 1300
    BindContext bind_ctx{&device, textures, tex_count};

    // --- Frame loop ---------------------------------------------------------
    //
    // A FIXED dt rather than a measured one. The renderer is vsync-locked to
    // 29.97 and the physics step is fixed (ADR-009); feeding a measured dt
    // into a fixed-step simulation just adds jitter without adding accuracy.
    const float kFixedDt = 1.0f / 30.0f;
    uint32_t frame = 0;

    for (;;) {
        float dt = kFixedDt;
        void* tick_args[1] = {&dt};
        if (!invoke_checked(tick, tick_args, "Tick")) {
            printf("[game] Tick threw on frame %u; stopping so the error is "
                   "visible rather than repeating forever.\n",
                   static_cast<unsigned>(frame));
            fatal("Tick");
            return 1;
        }

        // Animation runs between Update and LateUpdate, which is the
        // ordering Unity users rely on (M9 task 4). The host never called
        // this, so a scene's animators advanced by nothing at all.
        world.update_animators(dt);
        world.update_world_matrices();

        scene::RenderStats stats;
        if (!renderer.render(device, chain, world, programs, bind_texture,
                             &bind_ctx, &stats)) {
            fatal("scene render");
            return 1;
        }

        // The frame is complete: now show it.
        device.present();

        // A liveness marker the emulator harness can assert on, and a sign of
        // life in a log when someone is debugging a black screen. Once a
        // second is often enough to be useful and rare enough to be free.
        if (frame == PS2_GAME_READY_FRAME) {
            // What actually reached the screen. A scene can load perfectly
            // and draw nothing -- that is exactly how the skinned pass went
            // missing here -- and "drawn 0" says so in one line.
            printf("[game] drawn %u (culled %u, kicks %u), skinned %u in %u "
                   "batches\n",
                   static_cast<unsigned>(stats.drawn),
                   static_cast<unsigned>(stats.culled),
                   static_cast<unsigned>(stats.kicks),
                   static_cast<unsigned>(stats.skinned_drawn),
                   static_cast<unsigned>(stats.skin_batches));
            printf("PS2UR_TOKEN_GAME_OK frame %u\n",
                   static_cast<unsigned>(frame));
        }
        ++frame;
    }
}
