// The generic game host (plan section 13, M12): the ELF a Unity build
// produces.
//
// Derived from main_m7.cpp, which proved this bring-up sequence at M7. The
// differences are all subtractive -- what made that file a test harness is
// gone -- plus one addition: everything scene-specific now comes from
// game_config.h, which the build pipeline generates from the build profile.
//
// Boot sequence, in the order it has to happen:
//   1. Capture the stack bottom for bdwgc BEFORE anything allocates.
//   2. Bring up the GS.
//   3. Load the boot scene container into a scene::World.
//   4. bridge::bind_world, so managed Transform/GameObject resolve.
//   5. il2cpp_init, then find UnityEngine.Internal.Runtime.
//   6. CreateScript for every script component the scene carries.
//   7. Frame loop for as long as the console is on: Runtime.Tick(dt) ->
//      world matrices -> VU1 render.
//
// The loop runs forever by design. A shipped title never falls off the end
// of main(): returning hands control back to the BIOS, which shows the
// memory-card browser (verify-log M0).
#include <ps2ur/alloc.h>
#include <ps2ur/audio.h>
#include <ps2ur/bridge.h>
#include <ps2ur/input.h>
#include <ps2ur/dma_chain.h>
#include <ps2ur/gs_batch.h>
#include <ps2ur/gs_device.h>
#include <ps2ur/log.h>
#include <ps2ur/math.h>
#include <ps2ur/memcard.h>
#include <ps2ur/p2b.h>
#include <ps2ur/p2b_scene.h>
#include <ps2ur/scene_renderer.h>
#include <ps2ur/stream.h>
#include <ps2ur/phys.h>
#include <ps2ur/phys_bake.h>
#include <ps2ur/platform.h>
#include <ps2ur/vu_program.h>

#include <kernel.h>
#include <cstring>
#include <malloc.h>
#include <stdio.h>

#include "il2cpp-api.h"
#include "il2cpp-class-internals.h"

// Generated by the build pipeline from the build profile. Carries the boot
// scene name, the video mode and the memory budgets, so this file has
// nothing scene-specific compiled into it.
#include "game_config.h"

// Added in M12.5 task 3; a config generated by an older pipeline still
// builds, it just saves under the generic directory.
#ifndef PS2_GAME_SAVE_DIRECTORY
#define PS2_GAME_SAVE_DIRECTORY "PS2GAME"
#endif

using namespace ps2ur;

extern "C" u32 VuUnlit_CodeStart __attribute__((section(".vudata")));
extern "C" u32 VuUnlit_CodeEnd __attribute__((section(".vudata")));
extern "C" u32 VuUnlitTex_CodeStart __attribute__((section(".vudata")));
extern "C" u32 VuUnlitTex_CodeEnd __attribute__((section(".vudata")));
extern "C" u32 VuLitFog_CodeStart __attribute__((section(".vudata")));
extern "C" u32 VuLitFog_CodeEnd __attribute__((section(".vudata")));
extern "C" u32 VuSkin_CodeStart __attribute__((section(".vudata")));
extern "C" u32 VuSkin_CodeEnd __attribute__((section(".vudata")));
extern "C" u32 VuSkinTex_CodeStart __attribute__((section(".vudata")));
extern "C" u32 VuSkinTex_CodeEnd __attribute__((section(".vudata")));
extern "C" u32 VuLit_CodeStart __attribute__((section(".vudata")));
extern "C" u32 VuLit_CodeEnd __attribute__((section(".vudata")));

// bdwgc stack bound (see il2cpp-port/os/ps2/GcSupport.cpp).
extern "C" char* ps2ur_gc_stack_bottom;

namespace {

// The addresses scene::RendererPrograms defaults to; keep them in step.
constexpr uint32_t kAddrUnlit = 0;
constexpr uint32_t kAddrTex = 300;
constexpr uint32_t kAddrLit = 700;
constexpr uint32_t kAddrLitFog = 1000;
constexpr uint32_t kAddrSkin = 1300;
constexpr uint32_t kAddrSkinTex = 1500;

// VRAM holds the two colour buffers and the depth buffer, so what is left is
// what textures get. Eight 256x256 PSMT8 pages plus CLUTs fits comfortably.
constexpr uint32_t kMaxGpuTextures = 8;

struct GpuTexture {
    gfx::VramAlloc tex;
    gfx::VramAlloc clut;
    uint32_t w = 0, h = 0;
};

struct BindContext {
    gfx::GsDevice* device;
    GpuTexture* textures;
    uint32_t count;
};

bool bind_texture(void* user, uint32_t index, uint32_t* out_w, uint32_t* out_h)
{
    BindContext* ctx = static_cast<BindContext*>(user);
    if (index >= ctx->count) {
        return false; // not resident (over the 8-slot budget); say so
    }
    GpuTexture& t = ctx->textures[index];
    ctx->device->set_texture_indexed(t.tex, t.w, t.h, gfx::PixelFormat::PSMT8,
                                     t.clut, 256);
    *out_w = t.w;
    *out_h = t.h;
    return true;
}

uint32_t rd_u32(const uint8_t* p)
{
    return static_cast<uint32_t>(p[0]) | (static_cast<uint32_t>(p[1]) << 8) |
           (static_cast<uint32_t>(p[2]) << 16) |
           (static_cast<uint32_t>(p[3]) << 24);
}

// The scene arena.
//
// This was a 2 MB static array, on the reasoning that .bss is claimed before
// il2cpp asks for anything: at the profile's 6 MB default, on top of an 11 MB
// development ELF, that is 17 MB of 32 committed before the metadata (~1-2 MB)
// and the GC heap (4 MB) are allocated at all -- and il2cpp's metadata loader
// writes through the null it gets back rather than checking, so the symptom
// was stores to address 0x0 rather than an out-of-memory message
// (verify-log M12).
//
// The reasoning was right about .bss and wrong about 2 MB. A scene with one
// imported character in it is 5-6 MB, so a fixed 2 MB does not fail at the
// margin, it fails on the first real scene (verify-log M12.5).
//
// Taking it from the heap keeps what mattered -- nothing is committed that is
// not used -- while letting the profile's assetPoolMb actually govern the
// size, which it never did before. This runs before bridge::init(), so it is
// still ahead of every il2cpp allocation.
constexpr uint32_t kBootSceneArenaBytes = PS2_GAME_ASSET_POOL_BYTES;
alignas(16) gfx::Qword g_constants[17];

void set_float4(gfx::Qword& q, float x, float y, float z, float w)
{
    union {
        float f;
        uint32_t u;
    } cx{x}, cy{y}, cz{z}, cw{w};
    q.lo = static_cast<uint64_t>(cx.u) | (static_cast<uint64_t>(cy.u) << 32);
    q.hi = static_cast<uint64_t>(cz.u) | (static_cast<uint64_t>(cw.u) << 32);
}

const MethodInfo* find_runtime_method(const char* name, int params)
{
    const Il2CppDomain* domain = il2cpp_domain_get();
    size_t count = 0;
    const Il2CppAssembly** assemblies = il2cpp_domain_get_assemblies(domain, &count);
    for (size_t i = 0; i < count; ++i) {
        const Il2CppImage* image = il2cpp_assembly_get_image(assemblies[i]);
        Il2CppClass* klass =
            il2cpp_class_from_name(image, "UnityEngine.Internal", "Runtime");
        if (klass != nullptr) {
            const MethodInfo* method =
                il2cpp_class_get_method_from_name(klass, name, params);
            if (method != nullptr) {
                return method;
            }
        }
    }
    return nullptr;
}

// A managed call that reports rather than swallows. An exception escaping
// into native code with nobody looking is how a game "just stops"; printing
// it costs nothing and is the difference between a bug report and a mystery.
bool invoke_checked(const MethodInfo* method, void** args, const char* what)
{
    Il2CppException* exception = nullptr;
    il2cpp_runtime_invoke(const_cast<MethodInfo*>(method), nullptr, args, &exception);
    if (exception != nullptr) {
        static char message[512];
        il2cpp_format_exception(exception, message, sizeof(message));
        printf("[game] %s threw: %s\n", what, message);
        return false;
    }
    return true;
}

// A fatal error parks rather than returns, for the reason in the header.
void fatal(const char* what)
{
    printf("PS2UR_TOKEN_GAME_FAIL %s\n", what);
    SleepThread();
}

// Every Runtime entry point the host invokes, looked up once. A scene swap
// re-runs the same creates boot ran, so they live in one struct instead of
// a dozen locals.
struct RuntimeMethods {
    const MethodInfo* create_script;
    const MethodInfo* create_rigidbody;
    const MethodInfo* bind_colliders;
    const MethodInfo* create_animator;
    const MethodInfo* create_audio_source;
    const MethodInfo* create_audio_listener;
    const MethodInfo* create_particles;
    const MethodInfo* create_ui_graphic;
    const MethodInfo* create_ui_button;
    const MethodInfo* create_ui_slider;
    const MethodInfo* reset_for_scene_load;
    const MethodInfo* tick;

    bool lookup()
    {
        create_script = find_runtime_method("CreateScript", 2);
        create_rigidbody = find_runtime_method("CreateRigidbody", 5);
        bind_colliders = find_runtime_method("BindColliders", 0);
        create_animator = find_runtime_method("CreateAnimator", 1);
        create_audio_source = find_runtime_method("CreateAudioSource", 7);
        create_audio_listener = find_runtime_method("CreateAudioListener", 1);
        create_particles = find_runtime_method("CreatePS2ParticleSystem", 1);
        create_ui_graphic = find_runtime_method("CreateUIGraphic", 3);
        create_ui_button = find_runtime_method("CreateUIButton", 2);
        create_ui_slider = find_runtime_method("CreateUISlider", 7);
        reset_for_scene_load = find_runtime_method("ResetForSceneLoad", 0);
        tick = find_runtime_method("Tick", 1);
        return create_script != nullptr && tick != nullptr &&
               create_rigidbody != nullptr && bind_colliders != nullptr &&
               create_animator != nullptr && create_audio_source != nullptr &&
               create_audio_listener != nullptr &&
               create_particles != nullptr && create_ui_graphic != nullptr &&
               create_ui_button != nullptr && create_ui_slider != nullptr &&
               reset_for_scene_load != nullptr;
    }
};

// Static collision for a container. No PHYS section is a scene with no
// collision, which is fine; a malformed one is not.
bool load_scene_physics(const io::P2bFile& file, phys::StaticMesh* mesh)
{
    phys::BakeInfo bake;
    const char* phys_error = "";
    if (!phys::load_physics(file, mesh, &bake, &phys_error)) {
        printf("[game] collision: %s\n", phys_error);
        return false;
    }
    phys::set_static_mesh(mesh);
    printf("[game] collision: %u colliders, %u triangles, %u nodes\n",
           static_cast<unsigned>(bake.collider_count),
           static_cast<unsigned>(bake.triangle_count),
           static_cast<unsigned>(bake.node_count));
    return true;
}

// TEX sections into VRAM. base == 0 replaces: every previous allocation is
// freed first (the VRAM allocator does real frees). base > 0 appends, for
// an additive load whose material indices were rebased by that amount.
bool upload_scene_textures(gfx::GsDevice& device, const io::P2bFile& file,
                           GpuTexture* textures, uint32_t* io_count,
                           uint32_t base)
{
    if (base == 0u) {
        for (uint32_t t = 0; t < *io_count; ++t) {
            device.vram().free(textures[t].tex);
            device.vram().free(textures[t].clut);
            textures[t] = GpuTexture{};
        }
        *io_count = 0;
    }
    uint32_t tex_count = file.count_of(io::kSectionTex);
    if (base + tex_count > kMaxGpuTextures) {
        printf("[game] %u textures, only %u fit in VRAM; the rest will not "
               "be bound.\n",
               static_cast<unsigned>(base + tex_count),
               static_cast<unsigned>(kMaxGpuTextures));
        tex_count = kMaxGpuTextures - base;
    }
    for (uint32_t t = 0; t < tex_count; ++t) {
        // ONE PACKET PER TEXTURE. A 256x256 PSMT8 upload is 4096 qwords of
        // IMAGE data; several in one frame packet overflow it, and the
        // overflow reads exactly like running out of VRAM (verify-log
        // M12.5).
        device.begin_frame();
        device.clear(0, 0, 0);
        const io::P2bSection* sec = file.find(io::kSectionTex, t);
        const uint8_t* p = sec->data;
        GpuTexture& gt = textures[base + t];
        gt.w = rd_u32(p + 0);
        gt.h = rd_u32(p + 4);
        gt.tex = device.vram().alloc_buffer(gt.w, gt.h, gfx::PixelFormat::PSMT8,
                                            "game-tex");
        gt.clut = device.vram().alloc_buffer(16, 16, gfx::PixelFormat::PSMCT32,
                                             "game-clut");
        if (!gt.tex.valid() || !gt.clut.valid() ||
            !device.upload_texture(p + 16u + 1024u, gt.tex, gt.w, gt.h,
                                   gfx::PixelFormat::PSMT8) ||
            !device.upload_clut(reinterpret_cast<const uint32_t*>(p + 16u),
                                gt.clut, 256)) {
            printf("[game] texture %u (%ux%u) failed to upload: %s. Lower "
                   "Texture Max Size in the PS2 build profile, or use fewer "
                   "textures.\n",
                   static_cast<unsigned>(base + t), static_cast<unsigned>(gt.w),
                   static_cast<unsigned>(gt.h),
                   (!gt.tex.valid() || !gt.clut.valid())
                       ? "no room left in VRAM"
                       : "the GS packet overflowed");
            device.vram().debug_dump();
            device.end_frame();
            return false;
        }
        device.end_frame();
    }
    *io_count = base + tex_count;
    return true;
}

// SND clips into SPU2 memory. The blobs are used in place, which is one of
// the reasons a scene's arena outlives its load.
void upload_scene_clips(const io::P2bFile& file)
{
    if (!audio::initialized()) {
        return;
    }
    const io::P2bSection* snd = file.find(io::kSectionSound);
    if (snd == nullptr || snd->size < 16u) {
        return;
    }
    const uint32_t snd_clips = rd_u32(snd->data);
    uint32_t loaded = 0;
    for (uint32_t c = 0; c < snd_clips; ++c) {
        const uint8_t* record = snd->data + 16u + c * 16u;
        const uint32_t offset = rd_u32(record + 4);
        const uint32_t bytes = rd_u32(record + 8);
        if (offset + bytes > snd->size ||
            audio::load_clip(snd->data + offset, bytes) < 0) {
            printf("[game] SND clip %u did not load; sources naming it stay "
                   "silent.\n",
                   static_cast<unsigned>(c));
            continue;
        }
        ++loaded;
    }
    printf("[game] audio: %u of %u clips in SPU2 memory\n",
           static_cast<unsigned>(loaded), static_cast<unsigned>(snd_clips));
}

// The managed side of a world: every component object and script, created
// from the world's tables. 'from' is all zeros at boot and after a Single
// load; after an additive load it holds the table sizes from before the
// merge, so only the appended entries are created.
bool instantiate_managed(scene::World& world, const RuntimeMethods& rm,
                         const bridge::PreLoadCounts& from,
                         bool run_bind_colliders)
{
    if (run_bind_colliders &&
        !invoke_checked(rm.bind_colliders, nullptr, "BindColliders")) {
        return false;
    }
    for (uint32_t r = from.rigidbodies; r < world.rigidbody_count(); ++r) {
        const scene::RigidbodyRef& rb = world.rigidbody(r);
        int32_t handle = world.handle_of(rb.entity);
        float mass = rb.mass;
        float linear_damping = rb.linear_damping;
        float angular_damping = rb.angular_damping;
        int32_t flags = static_cast<int32_t>(rb.flags);
        void* args[5] = {&handle, &mass, &linear_damping, &angular_damping,
                         &flags};
        if (!invoke_checked(rm.create_rigidbody, args, "CreateRigidbody")) {
            return false;
        }
    }
    for (uint32_t a = from.animator_refs; a < world.animator_ref_count(); ++a) {
        int32_t handle = world.handle_of(world.animator_ref(a).entity);
        void* args[1] = {&handle};
        if (!invoke_checked(rm.create_animator, args, "CreateAnimator")) {
            return false;
        }
    }
    if (world.listener_entity() >= 0) {
        bridge::audio_set_listener_handle(
            world.handle_of(world.listener_entity()));
        int32_t handle = world.handle_of(world.listener_entity());
        void* args[1] = {&handle};
        if (!invoke_checked(rm.create_audio_listener, args,
                            "CreateAudioListener")) {
            return false;
        }
    }
    for (uint32_t s = from.audio_sources; s < world.audio_source_count(); ++s) {
        const scene::AudioSourceRef& src = world.audio_source(s);
        int32_t handle = world.handle_of(src.entity);
        int32_t clip = src.clip == 0xFFFFFFFFu
                           ? -1
                           : static_cast<int32_t>(src.clip);
        float volume = src.volume;
        int32_t flags = static_cast<int32_t>(src.flags);
        float min_d = src.min_distance;
        float max_d = src.max_distance;
        int32_t priority = src.priority;
        void* args[7] = {&handle, &clip,  &volume, &flags,
                         &min_d,  &max_d, &priority};
        if (!invoke_checked(rm.create_audio_source, args,
                            "CreateAudioSource")) {
            return false;
        }
    }
    for (uint32_t fx = from.particle_systems; fx < world.particle_system_count();
         ++fx) {
        int32_t handle = world.handle_of(world.particle_emitter(fx).entity);
        void* args[1] = {&handle};
        if (!invoke_checked(rm.create_particles, args,
                            "CreatePS2ParticleSystem")) {
            return false;
        }
    }
    if (world.particle_system_count() > 0) {
        printf("[game] %u particle systems\n",
               static_cast<unsigned>(world.particle_system_count()));
    }

    // Graphics first, then the buttons and sliders, so a Selectable's focus
    // tint finds the Graphic already registered on its GameObject. Buttons
    // and sliders reach PS2UINavigation in table order, which the exporter
    // wrote in hierarchy order -- the D-pad walks the menu top to bottom.
    uint32_t ui_buttons = 0;
    uint32_t ui_sliders = 0;
    for (uint32_t u = from.ui_elements; u < world.ui_element_count(); ++u) {
        const scene::UIElement& ui = world.ui_element(u);
        if (ui.w <= 0.0f || ui.h <= 0.0f) {
            continue; // role-only record: a Selectable with no graphic
        }
        int32_t handle = world.handle_of(ui.entity);
        int32_t element = static_cast<int32_t>(u);
        int32_t managed_kind = static_cast<int32_t>((ui.kind >> 8) & 0xFFu);
        void* args[3] = {&handle, &element, &managed_kind};
        if (!invoke_checked(rm.create_ui_graphic, args, "CreateUIGraphic")) {
            return false;
        }
    }
    for (uint32_t u = from.ui_elements; u < world.ui_element_count(); ++u) {
        const scene::UIElement& ui = world.ui_element(u);
        if (ui.role == 1u) {
            int32_t handle = world.handle_of(ui.entity);
            int32_t element = static_cast<int32_t>(u);
            void* args[2] = {&handle, &element};
            if (!invoke_checked(rm.create_ui_button, args, "CreateUIButton")) {
                return false;
            }
            ++ui_buttons;
        } else if (ui.role == 2u) {
            // The slider record's text bytes carry (f32 normalised value,
            // f32 max fill width); the fill rect's x/y/h come from the
            // linked fill element (docs/formats/p2b-container.md).
            int32_t handle = world.handle_of(ui.entity);
            int32_t fill = ui.link;
            float value;
            float max_w;
            memcpy(&value, ui.text + 0, 4);
            memcpy(&max_w, ui.text + 4, 4);
            float fill_x = 0.0f;
            float fill_y = 0.0f;
            float fill_h = 0.0f;
            if (fill >= 0 &&
                static_cast<uint32_t>(fill) < world.ui_element_count()) {
                const scene::UIElement& f =
                    world.ui_element(static_cast<uint32_t>(fill));
                fill_x = f.x;
                fill_y = f.y;
                fill_h = f.h;
            } else {
                fill = -1; // no fill rect authored; the value still works
            }
            void* args[7] = {&handle, &fill,   &fill_x, &fill_y,
                             &max_w,  &fill_h, &value};
            if (!invoke_checked(rm.create_ui_slider, args, "CreateUISlider")) {
                return false;
            }
            ++ui_sliders;
        }
    }
    if (world.ui_element_count() > 0) {
        printf("[game] ui: %u elements, %u buttons, %u sliders\n",
               static_cast<unsigned>(world.ui_element_count()),
               static_cast<unsigned>(ui_buttons),
               static_cast<unsigned>(ui_sliders));
    }

    if (world.audio_source_count() > 0 || world.listener_entity() >= 0) {
        printf("[game] %u audio sources, listener on entity %d\n",
               static_cast<unsigned>(world.audio_source_count()),
               world.listener_entity());
    }

    if (world.animator_ref_count() > 0 || world.skinned_renderer_count() > 0) {
        printf("[game] %u animator components, %u skinned renderers over %u "
               "meshes, %u skeletons, %u clips, %u animators\n",
               static_cast<unsigned>(world.animator_ref_count()),
               static_cast<unsigned>(world.skinned_renderer_count()),
               static_cast<unsigned>(world.skinned_mesh_count()),
               static_cast<unsigned>(world.skeleton_count()),
               static_cast<unsigned>(world.clip_count()),
               static_cast<unsigned>(world.animator_count()));
    }
    if (world.rigidbody_count() > 0) {
        printf("[game] %u rigidbodies\n",
               static_cast<unsigned>(world.rigidbody_count()));
    }

    for (uint32_t s = from.scripts; s < world.script_count(); ++s) {
        const scene::ScriptRef& script = world.script(s);
        Il2CppString* type_name = il2cpp_string_new(script.type_name);
        int32_t handle = world.handle_of(script.entity);
        void* args[2] = {type_name, &handle};
        printf("[game] script '%s' on entity %d\n", script.type_name,
               script.entity);
        if (!invoke_checked(rm.create_script, args, "CreateScript")) {
            return false;
        }
    }
    return true;
}

} // namespace

int main(void)
{
    int stackAnchor;
    ps2ur_gc_stack_bottom = reinterpret_cast<char*>(
        (reinterpret_cast<unsigned long>(&stackAnchor) + 128) & ~15UL);

    platform::init();
    printf("[game] %s starting\n", PS2_GAME_PRODUCT_NAME);

    // --- GS -----------------------------------------------------------------
    gfx::VideoConfig config;
    config.width = PS2_GAME_SCREEN_WIDTH;
    config.height = PS2_GAME_SCREEN_HEIGHT;

    gfx::GsDevice device;
    if (!device.init(config)) {
        fatal("gs device");
        return 1;
    }

    // --- Boot scene ---------------------------------------------------------
    Arena file_arena;
    void* file_arena_mem = memalign(16, kBootSceneArenaBytes);
    if (file_arena_mem == nullptr) {
        printf("[game] could not reserve the %u MB asset pool. Lower Asset "
               "Pool in the PS2 build profile, or the managed heap beside "
               "it.\n",
               static_cast<unsigned>(kBootSceneArenaBytes / (1024u * 1024u)));
        fatal("asset pool");
        return 1;
    }
    file_arena.init(file_arena_mem, kBootSceneArenaBytes);

    // A second arena of the same size, for SceneManager.LoadScene: the
    // loader reads the INCOMING scene here while the outgoing one -- whose
    // meshes live zero-copy in the other arena -- is still being drawn.
    // The two flip on every Single load. Reserved now, before il2cpp claims
    // the heap, so failure is a clear message rather than metadata writes
    // through a null (verify-log M12). A game that does not fit both keeps
    // running; it just cannot change scenes.
    void* scene_arenas[2] = {file_arena_mem, memalign(16, kBootSceneArenaBytes)};
    if (scene_arenas[1] == nullptr) {
        printf("[game] no RAM for a second scene arena; "
               "SceneManager.LoadScene is disabled. Lower Asset Pool in the "
               "PS2 build profile to enable scene transitions.\n");
    }

    // resolve_media_path tries host:, then the bare name, then
    // cdrom0:\NAME;1 -- so the same ELF runs from the emulator's host
    // filesystem during iteration and from the disc when burned, with no
    // rebuild (M10).
    char scene_path[96];
    if (!io::resolve_media_path(PS2_GAME_BOOT_SCENE, scene_path, sizeof(scene_path))) {
        printf("[game] boot scene '%s' not found on any media\n",
               PS2_GAME_BOOT_SCENE);
        fatal("boot scene missing");
        return 1;
    }
    printf("[game] boot scene: %s\n", scene_path);

    uint32_t file_size = 0;
    const void* file_data = io::load_file(scene_path, file_arena, &file_size);
    if (file_data == nullptr) {
        // The overwhelmingly likely cause is that the scene is bigger than the
        // pool, and the io layer has just printed both numbers. It cannot name
        // the setting to change -- it knows nothing about Unity -- so do it
        // here, where the profile that generated this build is known.
        printf("[game] the boot scene did not fit in the %u MB asset pool. "
               "Raise Asset Pool in the PS2 build profile.\n",
               static_cast<unsigned>(kBootSceneArenaBytes / (1024u * 1024u)));
        fatal("boot scene unreadable");
        return 1;
    }
    io::P2bFile file;
    if (!file.parse(file_data, file_size)) {
        printf("[game] container error: %s\n", file.error());
        fatal("boot scene malformed");
        return 1;
    }
    static scene::World world;
    if (!world.load(file)) {
        printf("[game] scene error: %s\n", world.error());
        fatal("boot scene load");
        return 1;
    }
    printf("[game] scene: %u entities, %u meshes, %u scripts\n",
           static_cast<unsigned>(world.entity_count()),
           static_cast<unsigned>(world.mesh_count()),
           static_cast<unsigned>(world.script_count()));

    if (!bridge::init()) {
        fatal("bridge");
        return 1;
    }
    bridge::bind_world(&world);
    if (scene_arenas[1] != nullptr) {
        // LoadScene reads into the arena the world is NOT in.
        bridge::bind_scene_buffer(scene_arenas[1], kBootSceneArenaBytes);
    }
    uint32_t arena_holds_world = 0;
    uint32_t seen_swaps = bridge::scene_swap_count();
    phys::init();

    // Collision. The BVH and the vertices are used straight out of the
    // container, so the mesh must outlive the world -- static storage, one
    // slot per arena, flipping with them on scene loads.
    //
    // A scene with no PHYS section loads fine and reports zero colliders;
    // not every scene has collision, and refusing to boot one would be
    // wrong. What is NOT fine is a section that is present and malformed.
    static phys::StaticMesh static_meshes[2];
    if (!load_scene_physics(file, &static_meshes[0])) {
        fatal("physics load");
        return 1;
    }

    // Platform services. input::init() brings up sio2man/padman and opens
    // both ports; without it every button reads false forever and
    // Input.GetButtonDown never fires -- the managed side polls happily and
    // gets nothing, which looks like a mapping bug rather than a missing
    // init. Audio is optional: a game with no sound should still boot.
    if (!input::init()) {
        printf("[game] pads failed to initialise; input will not work.\n");
    }
    // The async loader reads through the stream queue; without this,
    // SceneManager.LoadScene refuses every request. The M10 machinery was
    // complete and verified in samples -- and unreachable from a game,
    // because this call was missing (the M12 defect class, again).
    if (!stream::init()) {
        printf("[game] stream queue failed; scene loading will not work.\n");
    }
    // PlayerPrefs (M12.5 task 3): bring the card driver up, tell the bridge
    // where Save() writes, and hydrate the store from an existing save.
    // Every card state here is normal, not an error -- a fresh card simply
    // means an empty store, exactly like a first launch anywhere else.
    if (memcard::init()) {
        bridge::prefs_set_identity(PS2_GAME_SAVE_DIRECTORY,
                                   PS2_GAME_PRODUCT_NAME);
        const memcard::Status loaded =
            memcard::prefs::load(0, PS2_GAME_SAVE_DIRECTORY);
        printf("[game] prefs: %s (%u keys)\n", memcard::status_text(loaded),
               static_cast<unsigned>(memcard::prefs::count()));
    } else {
        printf("[game] memcard driver failed; PlayerPrefs will not persist.\n");
    }

    if (!audio::init()) {
        printf("[game] audio failed to initialise; the game will run silent.\n");
    } else {
        // SND clips into SPU2 memory (M12.5 task 2).
        upload_scene_clips(file);
    }

    // --- Managed runtime ----------------------------------------------------
    il2cpp_set_data_dir("host:");
    if (!il2cpp_init("IL2CPP Root Domain")) {
        fatal("il2cpp_init");
        return 1;
    }
    RuntimeMethods methods;
    if (!methods.lookup()) {
        // Almost always a stripping problem: the dispatcher is reached by
        // reflection, so it needs a link.xml entry to survive.
        printf("[game] UnityEngine.Internal.Runtime was not found. It is "
               "reached by reflection, so it must be preserved in "
               "link.xml.\n");
        fatal("Runtime methods missing");
        return 1;
    }

    // Everything managed, from the world's tables: physics bindings first
    // (a script's Start does GetComponent<Rigidbody>() on frame 1), then
    // components, then scripts. A scene swap re-runs exactly this.
    const bridge::PreLoadCounts kFromScratch = {};
    if (!instantiate_managed(world, methods, kFromScratch,
                             /*run_bind_colliders=*/true)) {
        fatal("instantiate managed");
        return 1;
    }

    // --- Textures -----------------------------------------------------------
    //
    // The host used to skip this entirely, so every TEX section a build
    // produced was dead weight on the disc and every textured material drew
    // with whatever happened to be in VRAM (verify-log M12.5).
    static GpuTexture textures[kMaxGpuTextures];
    uint32_t tex_count = 0;
    if (!upload_scene_textures(device, file, textures, &tex_count, 0)) {
        fatal("texture upload");
        return 1;
    }

    // --- VU programs + DMA chain -------------------------------------------
    //
    // All FIVE, at the addresses scene::RendererPrograms defaults to. Only
    // unlit and lit were uploaded before, which silently ruled out every
    // textured, fogged and skinned material a build could contain.
    vu::MicroProgram prog_unlit, prog_tex, prog_lit, prog_fog, prog_skin,
        prog_skin_tex;
    prog_unlit.set_blob(&VuUnlit_CodeStart, &VuUnlit_CodeEnd, kAddrUnlit);
    prog_tex.set_blob(&VuUnlitTex_CodeStart, &VuUnlitTex_CodeEnd, kAddrTex);
    prog_lit.set_blob(&VuLit_CodeStart, &VuLit_CodeEnd, kAddrLit);
    prog_fog.set_blob(&VuLitFog_CodeStart, &VuLitFog_CodeEnd, kAddrLitFog);
    prog_skin.set_blob(&VuSkin_CodeStart, &VuSkin_CodeEnd, kAddrSkin);
    prog_skin_tex.set_blob(&VuSkinTex_CodeStart, &VuSkinTex_CodeEnd,
                           kAddrSkinTex);
    if (!prog_unlit.upload() || !prog_tex.upload() || !prog_lit.upload() ||
        !prog_fog.upload() || !prog_skin.upload() || !prog_skin_tex.upload()) {
        fatal("vu programs");
        return 1;
    }
    // 16384 qwords (256 KB), matching samples/17-skinning -- the proven value
    // for character scenes. The 2048 this host inherited from main_m7 was
    // sized for a spinning cube: a single skinned batch is ~340 qwords (a
    // 24-matrix palette is 96 on its own, 48 5-qword vertices are 240), so
    // one imported character overflowed it mid-frame at 3101 qwords and the
    // frame was dropped (verify-log M12.5). This is a staging buffer in main
    // RAM, not a hardware limit; the cost of headroom is kilobytes.
    gfx::DmaChain chain;
    if (!chain.init(16384)) {
        fatal("dma chain");
        return 1;
    }

    if (!world.has_camera()) {
        printf("[game] the boot scene has no Camera; nothing could be drawn.\n");
        fatal("no camera");
        return 1;
    }
    // The M8/M9 frame path, rather than the hand-rolled loop this host used
    // to carry. That loop walked entities with a rigid mesh and nothing else,
    // so a scene's skinned characters were loaded, animated and never drawn,
    // and its textures never bound (verify-log M12.5). SceneRenderer already
    // does culling, the sorted opaque/transparent passes, material state,
    // fog and the skinned pass -- all of it built and verified in M8 and M9,
    // and all of it unreachable from a Unity build until now.
    scene::SceneRenderer renderer;
    if (!renderer.init_ui(device)) {
        printf("[game] ui overlay init failed; the canvas will not draw.\n");
    }
    scene::RendererPrograms programs; // 0 / 300 / 700 / 1000 / 1300
    BindContext bind_ctx{&device, textures, tex_count};

    // --- Frame loop ---------------------------------------------------------
    //
    // A FIXED dt rather than a measured one. The renderer is vsync-locked to
    // 29.97 and the physics step is fixed (ADR-009); feeding a measured dt
    // into a fixed-step simulation just adds jitter without adding accuracy.
    const float kFixedDt = 1.0f / 30.0f;
    uint32_t frame = 0;

    for (;;) {
        float dt = kFixedDt;
        void* tick_args[1] = {&dt};
        if (!invoke_checked(methods.tick, tick_args, "Tick")) {
            printf("[game] Tick threw on frame %u; stopping so the error is "
                   "visible rather than repeating forever.\n",
                   static_cast<unsigned>(frame));
            fatal("Tick");
            return 1;
        }

        // --- Scene transition (M12.5) -----------------------------------
        //
        // A managed SceneManager.LoadScene ACTIVATES inside Tick -- the
        // native world is already swapped by the time we are here, and the
        // old scene's managed objects ran this Tick against dead handles
        // (safe: every handle is generation-checked). Everything DERIVED
        // from the world is rebuilt now, between frames: managed objects,
        // physics, VRAM, SPU2. This block is why LoadScene works from a
        // game at all; the loader alone only swaps the tables.
        const uint32_t swaps_now = bridge::scene_swap_count();
        if (swaps_now != seen_swaps) {
            seen_swaps = swaps_now;
            const bool additive = bridge::scene_last_load_additive();
            const uint32_t loaded_arena = arena_holds_world ^ 1u;
            io::P2bFile next;
            if (scene_arenas[loaded_arena] == nullptr ||
                !next.parse(scene_arenas[loaded_arena], kBootSceneArenaBytes)) {
                printf("[game] swapped scene container unreadable: %s\n",
                       next.error());
                fatal("scene swap");
                return 1;
            }
            if (!additive) {
                // Old scene down: managed objects (OnDestroy fires), bodies,
                // voices and clips. PlayerPrefs survives by design.
                if (!invoke_checked(methods.reset_for_scene_load, nullptr,
                                    "ResetForSceneLoad")) {
                    fatal("scene reset");
                    return 1;
                }
                phys::clear_bodies();
                audio::reset_clips();
                if (!load_scene_physics(next, &static_meshes[loaded_arena]) ||
                    !upload_scene_textures(device, next, textures, &tex_count,
                                           0)) {
                    fatal("scene swap assets");
                    return 1;
                }
                upload_scene_clips(next);
                bind_ctx.count = tex_count;
                if (!instantiate_managed(world, methods, kFromScratch,
                                         /*run_bind_colliders=*/true)) {
                    fatal("scene swap instantiate");
                    return 1;
                }
                if (!world.has_camera()) {
                    printf("[game] the loaded scene has no Camera; nothing "
                           "could be drawn.\n");
                    fatal("scene swap camera");
                    return 1;
                }
                arena_holds_world = loaded_arena;
                // The arena the OLD world lived in is now the free one.
                bridge::bind_scene_buffer(scene_arenas[arena_holds_world ^ 1u],
                                          kBootSceneArenaBytes);
                printf("[game] scene swapped: %u entities, %u meshes, %u "
                       "scripts\n",
                       static_cast<unsigned>(world.entity_count()),
                       static_cast<unsigned>(world.mesh_count()),
                       static_cast<unsigned>(world.script_count()));
            } else {
                // Additive: the merge appended; create only what is new.
                // Static collision is NOT merged (the BVH is baked per
                // scene) -- an additive scene's PHYS section is ignored,
                // and both arenas are now live, so no further load has a
                // buffer until a Single load frees one.
                if (next.find(io::kSectionPhysics) != nullptr) {
                    printf("[game] additive scene has a PHYS section; static "
                           "collision cannot be merged and was ignored.\n");
                }
                if (!upload_scene_textures(device, next, textures, &tex_count,
                                           tex_count)) {
                    fatal("scene append assets");
                    return 1;
                }
                upload_scene_clips(next);
                bind_ctx.count = tex_count;
                if (!instantiate_managed(world, methods,
                                         bridge::scene_pre_load_counts(),
                                         /*run_bind_colliders=*/false)) {
                    fatal("scene append instantiate");
                    return 1;
                }
                bridge::bind_scene_buffer(nullptr, 0);
                printf("[game] scene appended: %u entities now; further "
                       "loads need a Single load first.\n",
                       static_cast<unsigned>(world.entity_count()));
            }
        }

        // Animation runs between Update and LateUpdate, which is the
        // ordering Unity users rely on (M9 task 4). The host never called
        // this, so a scene's animators advanced by nothing at all.
        world.update_animators(dt);
        world.update_world_matrices();
        // With the frame's final transforms: particles spawn from fresh
        // emitter matrices, then listener pose + spatial voices.
        world.update_particles(dt);
        bridge::audio_frame_update();

        scene::RenderStats stats;
        if (!renderer.render(device, chain, world, programs, bind_texture,
                             &bind_ctx, &stats)) {
            fatal("scene render");
            return 1;
        }

        // render() presents when its last kick has completed; a second
        // present here would flip the buffer twice per frame, alternating a
        // finished image with a half-drawn one (verify-log M12.5).

        // A liveness marker the emulator harness can assert on, and a sign of
        // life in a log when someone is debugging a black screen. Once a
        // second is often enough to be useful and rare enough to be free.
        if (frame == PS2_GAME_READY_FRAME) {
            // What actually reached the screen. A scene can load perfectly
            // and draw nothing -- that is exactly how the skinned pass went
            // missing here -- and "drawn 0" says so in one line.
            printf("[game] drawn %u (culled %u, kicks %u), skinned %u in %u "
                   "batches\n",
                   static_cast<unsigned>(stats.drawn),
                   static_cast<unsigned>(stats.culled),
                   static_cast<unsigned>(stats.kicks),
                   static_cast<unsigned>(stats.skinned_drawn),
                   static_cast<unsigned>(stats.skin_batches));
            printf("PS2UR_TOKEN_GAME_OK frame %u\n",
                   static_cast<unsigned>(frame));
        }
        ++frame;
    }
}
