// bridge: the managed <-> native boundary, per ADR-002 (plan section 5).
//
// ABI convention (every symbol in this module follows it):
//   - extern "C", C linkage, never name-mangled
//   - symbol prefix "ps2ur_"
//   - blittable-only parameters and returns: pointers, int8/16/32/64,
//     uint*, float. No C++ types, no structs-by-value across the boundary
//     unless fully blittable and layout-pinned. No doubles (section 3.1).
//   - no exceptions cross the boundary (runtime builds with -fno-exceptions)
//   - the managed side binds with [DllImport("__Internal")]; IL2CPP resolves
//     the symbols at static link time.
//
// The surface is defined in runtime/src/bridge/bridge-api.json and
// generated by tools/bindgen (prototypes: generated_bridge.h; C# externs:
// managed/PS2.UnityShim/Internal/Native.g.cs; docs: docs/bridge-surface.md).
// Implementations live in bridge_impl.cpp; ps2ur_debug_log stays in
// bridge.cpp as the hand-written diagnostic path.
#pragma once

namespace ps2ur {
namespace scene {
class World;
} // namespace scene

namespace bridge {

// Verifies the generated registration table (every boundary symbol linked
// and non-null). Call before the first managed frame.
bool init();
void shutdown();
bool initialized();

// The scene the entity/transform bridge operates on. Bind before managed
// code runs; unbound, every handle resolves dead (getters return identity,
// setters no-op) rather than faulting.
void bind_world(scene::World* world);
scene::World* world();

// Audio (M12.5 task 2). The host names the AudioListener's entity once at
// boot, and calls audio_frame_update() once per frame AFTER the managed
// tick: it poses the listener from that entity's world matrix and re-pans
// every live spatial voice from its entity -- natively, because doing it
// through the boundary would be one interop call per source per frame.
void audio_set_listener_handle(int entity_handle);
void audio_frame_update();

// PlayerPrefs (M12.5 task 3): the host names the on-card save directory
// (conventionally the disc serial) and browser title once at boot;
// ps2ur_prefs_save() writes there, port 0.
void prefs_set_identity(const char* directory, const char* title);

// Where an async scene load puts the container it reads (M10 task 5). The
// host program owns this memory because only it knows the memory budget;
// the managed SceneManager has no way to allocate 4 MB of EE RAM and no
// business deciding where it lives. Unbound, LoadSceneAsync fails cleanly
// and says so, rather than reading into nothing.
void bind_scene_buffer(void* buffer, unsigned int capacity);

} // namespace bridge
} // namespace ps2ur

extern "C" {

// Example/reference boundary function: managed Debug.Log lands here.
// 'utf8' is a NUL-terminated UTF-8 string owned by the caller for the duration
// of the call. Forwards to ps2ur::log at Info level. Null-safe.
void ps2ur_debug_log(const char* utf8);

} // extern "C"
