// bridge: the managed <-> native boundary, per ADR-002 (plan section 5).
//
// ABI convention (every symbol in this module follows it):
//   - extern "C", C linkage, never name-mangled
//   - symbol prefix "ps2ur_"
//   - blittable-only parameters and returns: pointers, int8/16/32/64,
//     uint*, float. No C++ types, no structs-by-value across the boundary
//     unless fully blittable and layout-pinned. No doubles (section 3.1).
//   - no exceptions cross the boundary (runtime builds with -fno-exceptions)
//   - the managed side binds with [DllImport("__Internal")]; IL2CPP resolves
//     the symbols at static link time.
//
// The surface is defined in runtime/src/bridge/bridge-api.json and
// generated by tools/bindgen (prototypes: generated_bridge.h; C# externs:
// managed/PS2.UnityShim/Internal/Native.g.cs; docs: docs/bridge-surface.md).
// Implementations live in bridge_impl.cpp; ps2ur_debug_log stays in
// bridge.cpp as the hand-written diagnostic path.
#pragma once

namespace ps2ur {
namespace scene {
class World;
} // namespace scene

namespace bridge {

// Verifies the generated registration table (every boundary symbol linked
// and non-null). Call before the first managed frame.
bool init();
void shutdown();
bool initialized();

// The scene the entity/transform bridge operates on. Bind before managed
// code runs; unbound, every handle resolves dead (getters return identity,
// setters no-op) rather than faulting.
void bind_world(scene::World* world);
scene::World* world();

} // namespace bridge
} // namespace ps2ur

extern "C" {

// Example/reference boundary function: managed Debug.Log lands here.
// 'utf8' is a NUL-terminated UTF-8 string owned by the caller for the duration
// of the call. Forwards to ps2ur::log at Info level. Null-safe.
void ps2ur_debug_log(const char* utf8);

} // extern "C"
